[dav_connection_name]
type = "dav"
username = "username"
password = "b64-encoded password"
url = "https://cloud.exmaple.com/remote.php/dav"
calname = "Name of the calendar"

[web_connection_name]
type = "web"
url = "url_to_calendar_subscription"
