# You can use it to add commands that run after AeroSpace startup.
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [

]

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]



start-at-login = true


enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 25

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Mouse movement
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

automatically-unhide-macos-hidden-apps = true

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 12
    inner.vertical =   12
    outer.left =       12
    outer.bottom =     12
    outer.top =        [ { monitor."built-in.*" = 16 }, 53 ]
    outer.right =      12

[workspace-to-monitor-force-assignment]
    4 = [ 'secondary', 'primary' ]
    5 = [ 'secondary', 'primary' ]

[mode.main.binding]

    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
    #                   sectionSign (ISO keyboards only, european keyboards only)
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right
    # All possible modifiers: cmd, alt, ctrl, shift

    ctrl-cmd-t = '''exec-and-forget osascript -e '
    tell application "iTerm2"
      create window with default profile
    end tell
    ''''

    ctrl-cmd-f = '''exec-and-forget osascript -e '
    tell application "finder"
        make new Finder window
        activate
    end tell
    ''''

    ctrl-cmd-k = '''exec-and-forget osascript -e '
    tell application "KeePassXC"
        try
            set miniaturized of windows to false -- most apps
        end try
        activate
    end tell
    ''''

    ctrl-alt-f = 'layout floating'
    ctrl-alt-shift-f = 'layout tiling'

    ctrl-alt-v = 'layout vertical'
    ctrl-alt-shift-v = 'layout horizontal'

    ctrl-alt-a = 'layout accordion'
    ctrl-alt-shift-a = 'layout tiles'
    
    ctrl-alt-b = 'balance-sizes'
    ctrl-alt-r = 'flatten-workspace-tree'

    ctrl-alt-s = 'fullscreen --no-outer-gaps'

    ctrl-alt-h = 'focus left'
    ctrl-alt-j = 'focus down'
    ctrl-alt-k = 'focus up'
    ctrl-alt-l = 'focus right'

    ctrl-alt-shift-h = 'move left'
    ctrl-alt-shift-j = 'move down'
    ctrl-alt-shift-k = 'move up'
    ctrl-alt-shift-l = 'move right'

    ctrl-alt-rightSquareBracket = 'resize smart +50' # plus on qwertz
    ctrl-alt-slash = 'resize smart -50' # minus on qwertz

    ctrl-alt-right = 'workspace --wrap-around next'
    ctrl-alt-left = 'workspace --wrap-around prev'

    # these are here to create the workspaces, since exec-and-forget doesn't create them
    keypad1 = 'workspace 1'
    keypad2 = 'workspace 2'
    keypad3 = 'workspace 3'
    keypad4 = 'workspace 4'
    keypad5 = 'workspace 5'

    ctrl-alt-1 = 'exec-and-forget bash -c "aerospace workspace 1 && sketchybar --trigger update_spaces"'
    ctrl-alt-2 = 'exec-and-forget bash -c "aerospace workspace 2 && sketchybar --trigger update_spaces"'
    ctrl-alt-3 = 'exec-and-forget bash -c "aerospace workspace 3 && sketchybar --trigger update_spaces"'
    ctrl-alt-4 = 'exec-and-forget bash -c "aerospace workspace 4 && sketchybar --trigger update_spaces"'
    ctrl-alt-5 = 'exec-and-forget bash -c "aerospace workspace 5 && sketchybar --trigger update_spaces"'

    ctrl-alt-shift-1 = 'exec-and-forget bash -c "aerospace move-node-to-workspace 1 && sketchybar --trigger update_spaces"'
    ctrl-alt-shift-2 = 'exec-and-forget bash -c "aerospace move-node-to-workspace 2 && sketchybar --trigger update_spaces"'
    ctrl-alt-shift-3 = 'exec-and-forget bash -c "aerospace move-node-to-workspace 3 && sketchybar --trigger update_spaces"'
    ctrl-alt-shift-4 = 'exec-and-forget bash -c "aerospace move-node-to-workspace 4 && sketchybar --trigger update_spaces"'
    ctrl-alt-shift-5 = 'exec-and-forget bash -c "aerospace move-node-to-workspace 5 && sketchybar --trigger update_spaces"'

    ctrl-alt-tab = 'workspace-back-and-forth'
    # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    # alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']
    ctrl-alt-h = ['join-with left', 'mode main']
    ctrl-alt-j = ['join-with down', 'mode main']
    ctrl-alt-k = ['join-with up', 'mode main']
    ctrl-alt-l = ['join-with right', 'mode main']


[[on-window-detected]]
    if.app-id = 'com.apple.finder'
    run = ['layout floating']
